apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xls.charts.helm.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/operator-framework/operator-sdk/pull/2703"
spec:
  group: charts.helm.k8s.io
  names:
    kind: Xl
    listKind: XlList
    plural: xls
    singular: xl
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Schema for the xls API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: defines the desired state of Xl
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: defines the observed state of Xl
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}

# Made with Bob
